# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kernel.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picinput = QtWidgets.QLabel(self.centralwidget)
        self.picinput.setGeometry(QtCore.QRect(40, 20, 231, 191))
        self.picinput.setText("")
        self.picinput.setPixmap(QtGui.QPixmap("input.jpg"))
        self.picinput.setObjectName("picinput")
        self.picoutput = QtWidgets.QLabel(self.centralwidget)
        self.picoutput.setGeometry(QtCore.QRect(380, 20, 231, 191))
        self.picoutput.setText("")
        self.picoutput.setPixmap(QtGui.QPixmap("input.jpg"))
        self.picoutput.setObjectName("picoutput")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 230, 191, 171))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.m1_1 = QtWidgets.QLineEdit(self.groupBox)
        self.m1_1.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.m1_1.setInputMask("")
        self.m1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_1.setObjectName("m1_1")
        self.M1_2 = QtWidgets.QLineEdit(self.groupBox)
        self.M1_2.setGeometry(QtCore.QRect(70, 30, 51, 21))
        self.M1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.M1_2.setObjectName("M1_2")
        self.M1_3 = QtWidgets.QLineEdit(self.groupBox)
        self.M1_3.setGeometry(QtCore.QRect(130, 30, 51, 21))
        self.M1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.M1_3.setObjectName("M1_3")
        self.M2_1 = QtWidgets.QLineEdit(self.groupBox)
        self.M2_1.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.M2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.M2_1.setObjectName("M2_1")
        self.M2_2 = QtWidgets.QLineEdit(self.groupBox)
        self.M2_2.setGeometry(QtCore.QRect(70, 60, 51, 21))
        self.M2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.M2_2.setObjectName("M2_2")
        self.M2_3 = QtWidgets.QLineEdit(self.groupBox)
        self.M2_3.setGeometry(QtCore.QRect(130, 60, 51, 21))
        self.M2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.M2_3.setObjectName("M2_3")
        self.M3_1 = QtWidgets.QLineEdit(self.groupBox)
        self.M3_1.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.M3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.M3_1.setObjectName("M3_1")
        self.M3_2 = QtWidgets.QLineEdit(self.groupBox)
        self.M3_2.setGeometry(QtCore.QRect(70, 90, 51, 21))
        self.M3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.M3_2.setObjectName("M3_2")
        self.M3_3 = QtWidgets.QLineEdit(self.groupBox)
        self.M3_3.setGeometry(QtCore.QRect(130, 90, 51, 21))
        self.M3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.M3_3.setObjectName("M3_3")
        self.apply = QtWidgets.QPushButton(self.groupBox)
        self.apply.setGeometry(QtCore.QRect(10, 130, 89, 25))
        self.apply.setToolTip("")
        self.apply.setObjectName("apply")
        self.Mrip = QtWidgets.QLineEdit(self.groupBox)
        self.Mrip.setGeometry(QtCore.QRect(130, 130, 51, 21))
        self.Mrip.setAlignment(QtCore.Qt.AlignCenter)
        self.Mrip.setObjectName("Mrip")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 0, 67, 17))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 0, 67, 17))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test my kernel"))
        self.groupBox.setTitle(_translate("MainWindow", "Kernel 3x3"))
        self.m1_1.setText(_translate("MainWindow", "0.1111"))
        self.M1_2.setText(_translate("MainWindow", "0.1111"))
        self.M1_3.setText(_translate("MainWindow", "0.1111"))
        self.M2_1.setText(_translate("MainWindow", "0.1111"))
        self.M2_2.setText(_translate("MainWindow", "0.1111"))
        self.M2_3.setText(_translate("MainWindow", "0.1111"))
        self.M3_1.setText(_translate("MainWindow", "0.1111"))
        self.M3_2.setText(_translate("MainWindow", "0.1111"))
        self.M3_3.setText(_translate("MainWindow", "0.1111"))
        self.apply.setText(_translate("MainWindow", "Apply"))
        self.Mrip.setToolTip(_translate("MainWindow", "repeat"))
        self.Mrip.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Input"))
        self.label_4.setText(_translate("MainWindow", "Output"))
